<?xml version="1.0" encoding="UTF-8"?>

<AnalyzerReport tool_version="0.14.0" tool_name="bandit" uuid="e20cb8ae-6314-4214-a89a-13814532efdc">
  <BugInstance id="1">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/bin/gip-validator.py</SourceFile>
        <StartLine>232</StartLine>
        <EndLine>232</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="2">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/bin/gip-validator.py</SourceFile>
        <StartLine>780</StartLine>
        <EndLine>780</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="3">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>138</StartLine>
        <EndLine>138</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="4">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>1071</StartLine>
        <EndLine>1071</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="5">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>1337</StartLine>
        <EndLine>1337</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="6">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>1669</StartLine>
        <EndLine>1669</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="7">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>1673</StartLine>
        <EndLine>1673</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="8">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/BeautifulSoup.py</SourceFile>
        <StartLine>1861</StartLine>
        <EndLine>1861</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="9">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/condor_common.py</SourceFile>
        <StartLine>20</StartLine>
        <EndLine>20</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_imports</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Using xml.sax to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax with the equivalent defusedxml package.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="10">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/condor_common.py</SourceFile>
        <StartLine>157</StartLine>
        <EndLine>157</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.sax.make_parser to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax.make_parser with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="11">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/condor_common.py</SourceFile>
        <StartLine>161</StartLine>
        <EndLine>161</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="12">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/condor_common.py</SourceFile>
        <StartLine>295</StartLine>
        <EndLine>295</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="13">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/condor_common.py</SourceFile>
        <StartLine>299</StartLine>
        <EndLine>299</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="14">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/bestman/BestmanInfo.py</SourceFile>
        <StartLine>178</StartLine>
        <EndLine>178</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Use of possibly insecure function - consider using safer ast.literal_eval.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="15">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/bestman/srm_ping.py</SourceFile>
        <StartLine>184</StartLine>
        <EndLine>184</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="16">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/bestman/srm_ping.py</SourceFile>
        <StartLine>202</StartLine>
        <EndLine>202</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="17">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfo.py</SourceFile>
        <StartLine>65</StartLine>
        <EndLine>65</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="18">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfo.py</SourceFile>
        <StartLine>100</StartLine>
        <EndLine>100</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="19">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfo19.py</SourceFile>
        <StartLine>27</StartLine>
        <EndLine>27</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="20">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfo19.py</SourceFile>
        <StartLine>327</StartLine>
        <EndLine>327</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="21">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfo19.py</SourceFile>
        <StartLine>372</StartLine>
        <EndLine>372</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="22">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfoProviderParser.py</SourceFile>
        <StartLine>5</StartLine>
        <EndLine>5</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_imports</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Using xml.sax to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax with the equivalent defusedxml package.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="23">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfoProviderParser.py</SourceFile>
        <StartLine>139</StartLine>
        <EndLine>139</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="24">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfoProviderParser.py</SourceFile>
        <StartLine>282</StartLine>
        <EndLine>282</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.sax.make_parser to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax.make_parser with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="25">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/DCacheInfoProviderParser.py</SourceFile>
        <StartLine>294</StartLine>
        <EndLine>294</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.sax.make_parser to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax.make_parser with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="26">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>33</StartLine>
        <EndLine>33</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="27">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>37</StartLine>
        <EndLine>37</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="28">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>41</StartLine>
        <EndLine>41</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="29">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>45</StartLine>
        <EndLine>45</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="30">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>49</StartLine>
        <EndLine>49</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="31">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>53</StartLine>
        <EndLine>53</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="32">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>121</StartLine>
        <EndLine>121</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="33">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>125</StartLine>
        <EndLine>125</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_no_shell</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Starting a process without a shell.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="34">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>155</StartLine>
        <EndLine>155</EndLine>
      </Location>
    </BugLocations>
    <BugCode>assert_used</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="35">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/admin.py</SourceFile>
        <StartLine>238</StartLine>
        <EndLine>238</EndLine>
      </Location>
    </BugLocations>
    <BugCode>assert_used</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="36">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/space_calculator.py</SourceFile>
        <StartLine>417</StartLine>
        <EndLine>417</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="37">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/space_calculator.py</SourceFile>
        <StartLine>430</StartLine>
        <EndLine>430</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="38">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/dcache/space_calculator.py</SourceFile>
        <StartLine>438</StartLine>
        <EndLine>438</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="39">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/cluster.py</SourceFile>
        <StartLine>45</StartLine>
        <EndLine>45</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="40">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/cluster.py</SourceFile>
        <StartLine>46</StartLine>
        <EndLine>46</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="41">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/condor.py</SourceFile>
        <StartLine>114</StartLine>
        <EndLine>114</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="42">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/generic_storage.py</SourceFile>
        <StartLine>60</StartLine>
        <EndLine>60</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="43">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/generic_storage.py</SourceFile>
        <StartLine>75</StartLine>
        <EndLine>75</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="44">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/generic_storage.py</SourceFile>
        <StartLine>178</StartLine>
        <EndLine>178</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="45">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/generic_storage.py</SourceFile>
        <StartLine>191</StartLine>
        <EndLine>191</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="46">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip/providers/sge.py</SourceFile>
        <StartLine>155</StartLine>
        <EndLine>155</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="47">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_cese_bind.py</SourceFile>
        <StartLine>97</StartLine>
        <EndLine>97</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="48">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_cese_bind.py</SourceFile>
        <StartLine>106</StartLine>
        <EndLine>106</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="49">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_cese_bind.py</SourceFile>
        <StartLine>133</StartLine>
        <EndLine>133</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="50">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_cluster.py</SourceFile>
        <StartLine>177</StartLine>
        <EndLine>177</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="51">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_cluster.py</SourceFile>
        <StartLine>178</StartLine>
        <EndLine>178</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="52">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_common.py</SourceFile>
        <StartLine>293</StartLine>
        <EndLine>293</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="53">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_common.py</SourceFile>
        <StartLine>834</StartLine>
        <EndLine>834</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="54">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_common.py</SourceFile>
        <StartLine>846</StartLine>
        <EndLine>846</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="55">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_common.py</SourceFile>
        <StartLine>940</StartLine>
        <EndLine>940</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Use of insecure and deprecated function (mktemp).</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="56">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_ldap.py</SourceFile>
        <StartLine>275</StartLine>
        <EndLine>275</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="57">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>204</StartLine>
        <EndLine>205</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="58">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>213</StartLine>
        <EndLine>213</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="59">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>251</StartLine>
        <EndLine>251</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="60">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>501</StartLine>
        <EndLine>501</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="61">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>523</StartLine>
        <EndLine>523</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="62">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>532</StartLine>
        <EndLine>532</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="63">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>540</StartLine>
        <EndLine>540</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="64">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_osg.py</SourceFile>
        <StartLine>594</StartLine>
        <EndLine>594</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="65">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_storage.py</SourceFile>
        <StartLine>206</StartLine>
        <EndLine>206</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Use of possibly insecure function - consider using safer ast.literal_eval.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="66">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_testing.py</SourceFile>
        <StartLine>74</StartLine>
        <EndLine>74</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="67">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_testing.py</SourceFile>
        <StartLine>152</StartLine>
        <EndLine>152</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="68">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_testing.py</SourceFile>
        <StartLine>172</StartLine>
        <EndLine>172</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="69">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_testing.py</SourceFile>
        <StartLine>277</StartLine>
        <EndLine>277</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="70">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_validate.py</SourceFile>
        <StartLine>69</StartLine>
        <EndLine>69</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="71">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/gip_validate.py</SourceFile>
        <StartLine>76</StartLine>
        <EndLine>76</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="72">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/ldap.py</SourceFile>
        <StartLine>164</StartLine>
        <EndLine>164</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="73">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/lsf_common.py</SourceFile>
        <StartLine>242</StartLine>
        <EndLine>242</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="74">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/pbs_common.py</SourceFile>
        <StartLine>474</StartLine>
        <EndLine>474</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="75">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/sets24.py</SourceFile>
        <StartLine>552</StartLine>
        <EndLine>552</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="76">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/sge_common.py</SourceFile>
        <StartLine>168</StartLine>
        <EndLine>168</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="77">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/sge_common.py</SourceFile>
        <StartLine>172</StartLine>
        <EndLine>172</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="78">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/sge_common.py</SourceFile>
        <StartLine>198</StartLine>
        <EndLine>198</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="79">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/sge_common.py</SourceFile>
        <StartLine>384</StartLine>
        <EndLine>384</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="80">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/slurm_common.py</SourceFile>
        <StartLine>347</StartLine>
        <EndLine>347</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="81">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/user_input.py</SourceFile>
        <StartLine>24</StartLine>
        <EndLine>24</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="82">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/xml_common.py</SourceFile>
        <StartLine>7</StartLine>
        <EndLine>7</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_imports</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Using xml.dom.minidom to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom with the equivalent defusedxml package.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="83">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/xml_common.py</SourceFile>
        <StartLine>9</StartLine>
        <EndLine>9</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_imports</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Using xml.sax to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax with the equivalent defusedxml package.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="84">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/xml_common.py</SourceFile>
        <StartLine>41</StartLine>
        <EndLine>41</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="85">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/xml_common.py</SourceFile>
        <StartLine>43</StartLine>
        <EndLine>43</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="86">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/lib/python/xml_common.py</SourceFile>
        <StartLine>59</StartLine>
        <EndLine>59</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Using xml.sax.make_parser to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.sax.make_parser with its defusedxml equivalent function.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="87">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/libexec/osg_info_wrapper.py</SourceFile>
        <StartLine>232</StartLine>
        <EndLine>232</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="88">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/libexec/osg_info_wrapper.py</SourceFile>
        <StartLine>510</StartLine>
        <EndLine>510</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="89">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/libexec/osg_info_wrapper.py</SourceFile>
        <StartLine>514</StartLine>
        <EndLine>514</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="90">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/libexec/osg_info_wrapper.py</SourceFile>
        <StartLine>536</StartLine>
        <EndLine>537</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_no_shell</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Starting a process without a shell.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="91">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/libexec/osg_info_wrapper.py</SourceFile>
        <StartLine>571</StartLine>
        <EndLine>571</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Use of insecure MD2, MD4, or MD5 hash function.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="92">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/providers/authorization_service.py</SourceFile>
        <StartLine>65</StartLine>
        <EndLine>65</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="93">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/gip/reporting/plugins/OIM_XML_Aggregator.py</SourceFile>
        <StartLine>6</StartLine>
        <EndLine>7</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_imports</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Using xml.dom.minidom to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom with the equivalent defusedxml package.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="94">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/compare_bdii_cemon.py</SourceFile>
        <StartLine>32</StartLine>
        <EndLine>32</EndLine>
      </Location>
    </BugLocations>
    <BugCode>blacklist_calls</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="95">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>28</StartLine>
        <EndLine>28</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="96">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>40</StartLine>
        <EndLine>40</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="97">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>60</StartLine>
        <EndLine>60</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="98">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>94</StartLine>
        <EndLine>94</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="99">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>109</StartLine>
        <EndLine>109</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="100">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>128</StartLine>
        <EndLine>128</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="101">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>198</StartLine>
        <EndLine>198</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="102">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/condor_test.py</SourceFile>
        <StartLine>206</StartLine>
        <EndLine>206</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="103">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/lsf_test.py</SourceFile>
        <StartLine>24</StartLine>
        <EndLine>24</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="104">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/lsf_test.py</SourceFile>
        <StartLine>32</StartLine>
        <EndLine>32</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="105">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>41</StartLine>
        <EndLine>41</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="106">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>63</StartLine>
        <EndLine>63</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="107">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>88</StartLine>
        <EndLine>88</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="108">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>101</StartLine>
        <EndLine>101</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="109">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>120</StartLine>
        <EndLine>120</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="110">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>139</StartLine>
        <EndLine>139</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="111">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>166</StartLine>
        <EndLine>166</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="112">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>188</StartLine>
        <EndLine>188</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="113">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>206</StartLine>
        <EndLine>206</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="114">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/pbs_test.py</SourceFile>
        <StartLine>226</StartLine>
        <EndLine>226</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="115">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/sge_test.py</SourceFile>
        <StartLine>28</StartLine>
        <EndLine>28</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="116">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/sge_test.py</SourceFile>
        <StartLine>36</StartLine>
        <EndLine>36</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="117">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/slurm_test.py</SourceFile>
        <StartLine>44</StartLine>
        <EndLine>44</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="118">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/slurm_test.py</SourceFile>
        <StartLine>60</StartLine>
        <EndLine>60</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="119">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/tempfile23.py</SourceFile>
        <StartLine>51</StartLine>
        <EndLine>51</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="120">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/tempfile23.py</SourceFile>
        <StartLine>138</StartLine>
        <EndLine>138</EndLine>
      </Location>
    </BugLocations>
    <BugCode>try_except_pass</BugCode>
    <BugSeverity>LOW</BugSeverity>
    <BugMessage>Try, Except, Pass detected.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="121">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/tempfile23.py</SourceFile>
        <StartLine>146</StartLine>
        <EndLine>146</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="122">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/tempfile23.py</SourceFile>
        <StartLine>146</StartLine>
        <EndLine>146</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="123">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_cesebind.py</SourceFile>
        <StartLine>31</StartLine>
        <EndLine>31</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="124">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_gip_common.py</SourceFile>
        <StartLine>127</StartLine>
        <EndLine>127</EndLine>
      </Location>
    </BugLocations>
    <BugCode>hardcoded_tmp_directory</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Probable insecure usage of temp file/directory.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="125">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_se.py</SourceFile>
        <StartLine>31</StartLine>
        <EndLine>31</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="126">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_site_name.py</SourceFile>
        <StartLine>17</StartLine>
        <EndLine>17</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="127">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_software.py</SourceFile>
        <StartLine>28</StartLine>
        <EndLine>28</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="128">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_subclusters.py</SourceFile>
        <StartLine>27</StartLine>
        <EndLine>27</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="129">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_topology.py</SourceFile>
        <StartLine>25</StartLine>
        <EndLine>25</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugInstance id="130">
    <Methods></Methods>
    <BugLocations>
      <Location id="1" primary="true">
        <SourceFile>gip-1.3.11/test/test_topology.py</SourceFile>
        <StartLine>32</StartLine>
        <EndLine>32</EndLine>
      </Location>
    </BugLocations>
    <BugCode>start_process_with_a_shell</BugCode>
    <BugSeverity>MEDIUM</BugSeverity>
    <BugMessage>Starting a process with a shell: check for injection.</BugMessage>
    <BugTrace>
      <BuildId>0</BuildId>
      <AssessmentReportFile>pytool-python2/report.json</AssessmentReportFile>
    </BugTrace>
  </BugInstance>
  <BugSummary>
    <BugCategory group="" code="assert_used" count="2" bytes="1276" />
    <BugCategory group="" code="blacklist_calls" count="16" bytes="10622" />
    <BugCategory group="" code="blacklist_imports" count="5" bytes="3466" />
    <BugCategory group="" code="hardcoded_tmp_directory" count="9" bytes="5391" />
    <BugCategory group="" code="start_process_with_a_shell" count="39" bytes="23346" />
    <BugCategory group="" code="start_process_with_no_shell" count="2" bytes="1183" />
    <BugCategory group="" code="try_except_pass" count="57" bytes="32567" />
  </BugSummary>
</AnalyzerReport>